config/routes.rb
Bookmarks::Application.routes.draw do
  get "site/index"
  devise_for :users
  resources :bookmarks

   root 'site#index'

  

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :user
  
  validates :user_id, presence: true
  validates :title, presence: true, length: {minimum: 8}
  validates :url, presence: true, format: {with: Regexp.new(URI::regexp(%w(http https)))}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /bookmarks
  # GET /bookmarks.json
  def index
    @bookmarks = current_user.bookmarks.all
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = current_user.bookmarks.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = current_user.bookmarks.new(bookmark_params)

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bookmark }
      else
        format.html { render action: 'new' }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
     unless  @bookmark = current_user.bookmarks.where(id: params[:id]).first
       flash[:alert] = "Bookmarks not found."
       redirect_to root_path
     end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookmark_params
      params.require(:bookmark).permit(:title, :url)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    @bookmarks = Bookmark.order('created_at desc')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for(@bookmark) do |f| %>
<%= f.error_notification %>
<div class="form-inputs">
  <%= f.input :title %>
  <%= f.input :url %>
</div>
<div class="from-actions">

  <%= f.button :submit %>
</div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Editing bookmark</h1>

<%= render 'form' %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<h1>Listing bookmarks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><%= bookmark.title %></td>
        <td><%= bookmark.url %></td>
        <td><%= link_to 'Show', bookmark %></td>
        <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
        <td><%= link_to 'Destroy', bookmark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bookmark', new_bookmark_path %>

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>

<%= render 'form' %>

<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bookmark.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @bookmark.url %>
</p>

<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/site/index.html.erb
<% if current_user %>
  <h2>Latest Bookmarks</h2>
  <table style="width: 100%">
    <thead>
      <tr>
        <th>Url</th>
      </tr>
    </thead>
 
    <tbody>
      <% @bookmarks.each do |bookmark| %>
        <tr>
          <td><%= link_to bookmark.title, bookmark.url %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
 
<% else %>
  <div class="panel">
    <h1>Share your bookmarks!</h1>
    <p>A simple app to track and share your beloved bookmarks with others.</p>
    <%= link_to "Get started today", new_user_registration_path, :class => "button button-large" %>
  </div>
 
  <hr>
 
  <div class="row">
    <div class="large-8 columns">
      <h3>12 Devs of Summer</h3>
      <p>
      12 Devs is an evolution of the 12 Devs of Xmas, a way to bring more cool web development articles to you throughout the year. However 12 Devs won’t just be about the tutorial and tips articles, we’re also going to be bringing you some great new features and events.
      </p>
      <p><a class="" href="http://12devs.co.uk" target="_blank">Learn more</a>.</p>
    </div>
    <div class="large-4 columns">
      <h3>About this app</h3>
      <p>This is a tutorial app developed by <a href="http://andreapavoni.com" target="_blank">Andrea Pavoni</a> as a companion to the rails article. Check the source code on <a href="http://github.com/apeacox/12dos-bookmarks" target="_blank">GitHub</a>. </p>
    </div>
  </div>
<% end %>